---
title: Transform Tutoring
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@transformtutoring.org
description: "Bay Area tutoring including SAT & ACT tutoring, math tutoring, writing
  tutoring, english tutoring, and college admissions counseling. \n"
author: transformtutoring
keyword: jekyll
baseurl: ''
url: ''
github_username: na
markdown: kramdown
gems:
- jekyll-feed
exclude:
- agency-jekyll-theme.gemspec
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
